include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_double_and_int_checks: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    prefer_foreach: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true