name: mak_blog
description: Mak Blog
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  firebase_core: 2.13.1
  go_router: 7.1.1
  cloud_firestore: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
